######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 27 10:56:08 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += image.h jpeg_viewer.h mainwindow.h
SOURCES += dct.cc image.cc jpeg.cc jpeg_viewer.cc mainwindow.cc
