######################################################################
# Automatically generated by qmake (2.01a) man mar 3 18:55:48 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dct.h huffman.h huffman_tables.h image.h jpeg_viewer.h mainwindow.h
SOURCES += dct.cc huffman.cc image.cc jpeg.cc jpeg_viewer.cc mainwindow.cc
