######################################################################
# Automatically generated by qmake (2.01a) søn mar 2 13:38:33 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input

HEADERS += dct.h image.h jpeg_viewer.h mainwindow.h huffman.h huffman_tables.h
SOURCES += dct.cc image.cc jpeg.cc jpeg_viewer.cc mainwindow.cc huffman.cc
